# Generated by Django 4.1.1 on 2022-10-26 20:51

import django.core.validators
from django.db import migrations, models
import my_music_app_exam.music.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[(1, 'Pop Music'), (2, 'Jazz Music'), (3, 'R&B Music'), (4, 'Rock Music'), (5, 'Country Music'), (6, 'Dance Music'), (7, 'Hip Hop Music'), (8, 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[my_music_app_exam.music.validators.validate_value_is_above_zero])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app_exam.music.validators.validate_if_value_contains_only_nums_chars_and_underscore])),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(blank=True, null=True, validators=[my_music_app_exam.music.validators.validate_value_is_above_zero])),
            ],
        ),
    ]
